# Generated by Django 2.2.14 on 2021-06-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210623_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.ManyToManyField(related_name='addresses', to='addresses.Address'),
        ),
    ]
