# Generated by Django 2.2.14 on 2021-06-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210624_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.ManyToManyField(related_name='users', to='addresses.Address'),
        ),
    ]
